#!/usr/bin/env python3
# Convert a (variable) TTF to an Adafruit GFX font header.
# Each glyph is byte-aligned so the stock Adafruit_GFX drawChar renders it as-is.
import sys, freetype
def conv(ttf, px, name, weight=None, first=0x20, last=0x7E):
    face = freetype.Face(ttf)
    if weight is not None:
        try: face.set_var_design_coords([float(weight)])
        except Exception as e: sys.stderr.write(f"var set failed: {e}\n")
    face.set_pixel_sizes(0, px)
    bitmap = bytearray(); glyphs = []
    for code in range(first, last+1):
        face.load_char(chr(code), freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
        g = face.glyph; bm = g.bitmap
        w, h, pitch = bm.width, bm.rows, bm.pitch
        offset = len(bitmap); acc = 0; nbits = 0
        for y in range(h):
            for x in range(w):
                byte = bm.buffer[y*pitch + (x >> 3)]
                acc = (acc << 1) | (1 if (byte & (0x80 >> (x & 7))) else 0); nbits += 1
                if nbits == 8: bitmap.append(acc); acc = 0; nbits = 0
        if nbits: bitmap.append(acc << (8 - nbits))
        glyphs.append((offset, w, h, g.advance.x >> 6, g.bitmap_left, 1 - g.bitmap_top))
    yadv = face.size.height >> 6
    o = [f"// {name}: {ttf.split('/')[-1]} px={px} wght={weight} - generated by ttf2gfx.py",
         "#pragma once", "#include <Adafruit_GFX.h>",
         f"const uint8_t {name}Bitmaps[] PROGMEM = {{",
         "  " + ",".join(f"0x{b:02X}" for b in bitmap), "};",
         f"const GFXglyph {name}Glyphs[] PROGMEM = {{"]
    for (off,w,h,xa,xo,yo) in glyphs: o.append(f"  {{ {off}, {w}, {h}, {xa}, {xo}, {yo} }},")
    o += ["};", f"const GFXfont {name} PROGMEM = {{",
          f"  (uint8_t*){name}Bitmaps, (GFXglyph*){name}Glyphs, 0x{first:02X}, 0x{last:02X}, {yadv} }};"]
    capA = glyphs[0x41-first]
    sys.stderr.write(f"{name}: px={px} wght={weight} advance={capA[3]}px capH={capA[2]}px yAdv={yadv} bytes={len(bitmap)}\n")
    return "\n".join(o)+"\n"
if __name__=="__main__":
    ttf, px, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    weight = sys.argv[4] if len(sys.argv)>4 else None
    open(name+".h","w").write(conv(ttf, px, name, weight))
